- type: job
  id: MedicalDoctor
  name: job-name-doctor
  description: job-description-doctor
  playTimeTracker: JobMedicalDoctor
#  requirements:
#    - !type:DepartmentTimeRequirement
#      department: Medical
#      time: 1800
  startingGear: DoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-cmo
  setPreference: true
  access:
  - Medical
  - Maintenance
  - External
  - Chemistry

- type: startingGear
  id: DoctorGear
  equipment:
    jumpsuit: ClothingShirtScrubsBlue
    lowerClothing: ClothingPantsScrubsBlue
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLab
    id: MedicalPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    pocket2: SurvivalKnife
  innerClothingSkirt: ClothingUniformJumpskirtMedicalDoctor
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
