- type: job
  id: Pilot
  name: job-name-pilot
  playTimeTracker: JobPilot
  startingGear: PilotGear
  icon: "JobIconCaptain"
  supervisors: job-supervisors-captain
  setPreference: true
  accessGroups:
    - AllAccess
  requirements:
    - !type:RoleTimeRequirement
      role: JobEkrixiCommandWhitelist
      time: 1

- type: startingGear
  id: PilotGear
  equipment:
    head: ClothingHeadHatAnimalHeadslime
    jumpsuit: ClothingShirtTShirtCommand
    lowerClothing: ClothingPantsRippedJeans
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatTrenchLight
    eyes: ClothingEyesGlassesPilot
    id: PilotPDA
    ears: ClothingHeadsetAltCommand
    belt: BasicPager
    pocket1: WeaponRevolverDeckard
    pocket2: ClothingEyesGlassesSunglasses
  innerClothingSkirt: ClothingPantsPilot
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
