- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
#  requirements:
#    - !type:DepartmentTimeRequirement
#      department: Security
#      time: 3600 #1 hr
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  setPreference: true
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SecurityOfficerGear
  equipment:
    jumpsuit: ClothingShirtTShirtBlack
    lowerClothing: ClothingPantsRippedJeans
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsMercFilled
    eyes: ClothingEyesGlassesSunglasses
    head: ClothingHeadHatBlacksoft
    gloves: ClothingHandsMercGlovesCombat
    outerClothing: ClothingOuterArmorBasic
    id: SecurityPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltMilitaryWebbing
    pocket1: Handcuffs
    suitstorage: WeaponShotgunDoubleBarreled
#  innerClothingSkirt: ClothingUniformJumpskirtSec
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
